### ISSUE TITLE
PSR conflict with Symfony

### ISSUE THREAD

**Issue by pvdleek** [joseluisq/alpine-php-fpm#40]
Hi, I ran into an issue today that the PSR extension conflicts with the Symfony cache component. I therefore had to remove PSR, but as there is no "docker-php-ext-disable" (and it will not be there, see https://github.com/docker-library/php/issues/220#issuecomment-353677238) I tried "pecl uninstall psr". Unfortunately that created another issue:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'psr' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20230831/psr (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20230831/psr: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20230831/psr.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20230831/psr.so: No such file or directory)) in Unknown on line 0
```
I could of course create a PR for the removal of PSR, but it might be more interesting to have a ENV variable control the installation of PSR (and maybe other extensions).

How do you feel about this?

**Comment by joseluisq** [comment]
It sounds not bad. I'm thinking of something like an ENV to pass a list of extensions (not just PSR) to disable at start-up  (remove them eventually).

**Comment by joseluisq** [comment]
On the other hand, being able to turn off extensions at build time should be also a nice feature since not all users want the same amount of extensions to use.

**Comment by joseluisq** [comment]
Feel free to propose something in either case.

**Comment by pvdleek** [comment]
I think an ENV would do just fine. At this point I would go for a blacklist to disable certain extensions. So in my case I would pass on an ENV "EXTENSION_BLACKLIST" with value "psr" or something like that.
In the mean time I made a copy of this repo, removed PSR and published my own base-image, but I'd rather go back to this repo with the possibility to disable PSR ;)

**Comment by pvdleek** [comment]
Any progress on this? ;)

**Comment by joseluisq** [comment]
Unfortunately, I couldn't find the time, but if you want to help, just let me know.
Let's see how it goes in the next few days.

**Comment by joseluisq** [comment]
@pvdleek https://github.com/joseluisq/alpine-php-fpm/issues/40 will add support for disabling extensions. Feel free to test it.

**Comment by reinout** [comment]
I'm now working on a docker made by @pvdleek :-) The fix works, but only when *running* the docker.
Our `Dockerfile` uses symphony/composer (I'm not that good in php, sorry, so I might have messed up the terms). The Dockerfile, thus, calls `RUN php bin/console assets:install html`, which fails with a `Fatal error: declaration of CacheItem::expiresAt() must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt()`, which is psr-related [according to this symfony bug report](https://github.com/symfony/symfony/issues/49984).

So I'd actually already need the disabling when building the docker.

I'm now calling the entrypoint instead of php in my dockerfile, which deactivates the extension directly:

    RUN /entrypoint.sh bin/console assets:install html

I thought it best to post that workaround here :-)
